config/routes.rb
# For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
Rails.application.routes.draw do
  get 'home/index'

  resources :recipes do
    resources :ingredients
  end

  root 'home#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/ingredient.rb
class Ingredient < ApplicationRecord
  belongs_to :recipe
end

app/models/recipe.rb
class Recipe < ApplicationRecord
  has_many :ingredients, :dependent => :delete_all
  accepts_nested_attributes_for :ingredients, reject_if: :all_blank
  validates :title, presence: true, length: {minimum: 4}
  validates :author, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/ingredients_controller.rb
class IngredientsController < ApplicationController

  def create
    @recipe = Recipe.find(params[:recipe_id])
    @ingredient = @recipe.ingredients.create(ingredient_params)
    redirect_to recipe_path(@recipe)
  end

  private
  def ingredient_params
    params.require(:ingredient).permit(:name, :amount, :uom)
  end
end

app/controllers/recipes_controller.rb
class RecipesController < ApplicationController
  def index
    @recipes = Recipe.all
  end

  def show
    @recipe = Recipe.find(params[:id])
  end

  def new
    @recipe = Recipe.new
    @recipe.ingredients.build
  end

  def edit
    @recipe = Recipe.find(params[:id])
    @recipe.ingredients.build
  end

  def create
    @recipe = Recipe.new(recipe_params)
    if @recipe.save
      redirect_to @recipe
    else
      render 'new'
    end
  end

  def update
    @recipe = Recipe.find(params[:id])

    if @recipe.update(recipe_params)
      redirect_to @recipe
    else
      render 'edit'
    end
  end

  def destroy
    @recipe = Recipe.find(params[:id])
    @recipe.destroy

    redirect_to @recipe
  end

  private
  def recipe_params
    params.require(:recipe).permit(:title, :author, :note,
                                   ingredients_attributes: [:id, :name, :amount, :uom])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/ingredients_helper.rb
module IngredientsHelper
end

app/helpers/recipes_helper.rb
module RecipesHelper
end

app/views/home/index.html.erb
<h1> Welcome to the Meal Planner</h1>
<%= link_to 'See Recipes', controller: 'recipes' %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MealPlannerSql</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/recipes/_form.html.erb
<%= form_for(@recipe) do |form| %>
  <% if @recipe.errors.any? %>
    <div id = "error_explanation">
      <h2>
        <%= pluralize(@recipe.errors.count, "error") %>
        prohibited this recipe from being saved:
      </h2>
      <ul>
        <%@recipe.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <p>
    <%= form.label :title  %><br>
    <%= form.text_field :title %>
  </p>

  <p>
    <%= form.label :author  %><br>
    <%= form.text_field :author %>
  </p>

  <p>
    <%= form.label :note %><br>
    <%= form.text_area :note %>
  </p>

  <table>
    <tr>
      <th> Name </th>
      <th> Amount </th>
      <th> UOM </th>
    </tr>

    <% @recipe.ingredients.each do |ingredient| %>
      <tr>
        <td><%= ingredient.name %></td>
        <td><%= ingredient.amount  %></td>
        <td><%= ingredient.uom %></td>
      </tr>

      </table>

    <% end %>

  <h2>Add an Ingredient: </h2>
  <%= form.fields_for :ingredients do |new| %>
    <p>
      <%= new.label :name %><br>
      <%= new.text_field :name %>
    </p>
    <p>
      <%= new.label :amount %><br>
      <%= new.number_field :amount %>
    </p>
    <p>
      <%= new.label :uom %><br>
      <%= new.text_field :uom %>
    </p>
    <p>
      <%= new.submit %>
    </p>
  <% end %>

  <p>
    <%= form.submit %>
  </p>

<% end %>

app/views/recipes/edit.html.erb
<h1> Edit Recipe </h1>

<%= render 'form' %>

<%= link_to 'Back', recipes_path %>

app/views/recipes/index.html.erb
<h1>Listing Recipes</h1>

<%= link_to 'New Recipe', new_recipe_path %>

</br>

<table>
  <tr>
    <th>Title</th>
    <th>Author</th>
    <th>Note</th>
    <th colspan="3"></th>
  </tr>

  <% @recipes.each do |recipe| %>
    <tr>
      <td><%= recipe.title %></td>
      <td><%= recipe.author  %></td>
      <td><%= recipe.note %></td>
      <td><%= link_to 'Show', recipe_path(recipe) %></td>
      <td><%= link_to 'Edit', edit_recipe_path(recipe) %></td>
      <td><%= link_to 'Destroy', recipe_path(recipe),
          method: :delete, data: {confirm: 'Are you sure?'} %></td>
    </tr>
  <% end %>
</table>

</br>

<%= link_to 'Home', home_index_path %>

app/views/recipes/new.html.erb
<h1>New Recipe</h1>

<%= render 'form' %>

<%= link_to 'Back', recipes_path %>

app/views/recipes/show.html.erb
<p>
  <strong> Title: </strong>
  <%= @recipe.title %>
</p>

<p>
  <strong>Author: </strong>
  <%= @recipe.author %>
</p>

<p>
  <strong> Note: </strong>
  <%= @recipe.note  %>
</p>


<table>
  <h2>Ingredients</h2>
  <tr>
  <th>Name</th>
  <th>Amount</th>
  <th>UOM</th>
  </tr>

<% @recipe.ingredients.each do |ingredient| %>
    <tr>
      <td><%= ingredient.name %></td>
      <td><%= ingredient.amount  %></td>
      <td><%= ingredient.uom %></td>
    </tr>

<% end %>

</table>

</br>

<%= link_to 'Edit', edit_recipe_path(@recipe) %>
<%= link_to 'Back', recipes_path %>